theme: jekyll-theme-minimal
navbar:
  title: "Inicio"
  left:
    - text: "Estadísticas COVID-19"
      href: status_covid19.html
    - text: "Cómo participar"
      href: como-participar.md
    - text: "Proyecciones Balcarce"
      href: proyecciones_balcarce.html
    - text: "Sobre nosotros"
      href: about_us.html
    - text: "Nuestra organización"
      href: organiza_vete.html
